### PR TITLE
Update docs of deep lineage to version 0.1.0

### PR DESCRIPTION
**Pull request by stefanhahmann**
* Adds additional contents
* Remove obsolete contents
* Change from single page approach to multi page approach
  * Structuring the contents in multiple sub page seems reasonable, since the single page used to contain a lot already
  * I am a bit unsure, if I have structured the sub pages in the way that is intended by the template. I would need to check this, once this is online on readthedocs or is there any way to test this outside this PR?

### CODE REVIEW

**Comment by stefanhahmann** [comment]
Hi @tinevez
I wanted to send you a short reminder about this. Mastodon-Deep-Lineage 0.1.0 has been out for a while. Thus, I would appreciate, if the online docs could get in sync with it.

**Comment by tinevez** [comment]
Hello 
I merged them but it seems on the doc online that some pages are missing. Did I miss something?

**Comment by tinevez** [comment]
Yes Sphinx gives me several warnings that explain why:

```sphinx
❯ sphinx-build -a . /tmp/mydocs
Running Sphinx v7.2.6
making output directory... done
myst v2.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'attrs_inline'}, disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
building [mo]: all of 0 po files
writing output... 
building [html]: all source files
updating environment: [new config] 31 added, 0 changed, 0 removed
reading sources... [100%] index
/Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/classification/readme.md:1: WARNING: Document headings start at H2, not H1 [myst.header]
/Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/export/readme.md:1: WARNING: Document headings start at H2, not H1 [myst.header]
/Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/features/readme.md:1: WARNING: Document headings start at H2, not H1 [myst.header]
/Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/import/readme.md:1: WARNING: Document headings start at H2, not H1 [myst.header]
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/classification/readme.md: WARNING: document isn't included in any toctree
/Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/export/readme.md: WARNING: document isn't included in any toctree
/Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/features/readme.md: WARNING: document isn't included in any toctree
/Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/import/readme.md: WARNING: document isn't included in any toctree
done
preparing documents... done
copying downloadable files... [100%] docs/partE/TPietzschConvexPolytopes.pdf
copying static files... done
copying extra files... done
done
writing output... [100%] index
WARNING: Domain 'javasphinx.domain::java' has not implemented a `resolve_any_xref` method [myst.domains]
/Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/readme.md:12: WARNING: 'myst' cross-reference target not found: 'installation-instructions' [myst.xref_missing]
/Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/readme.md:13: WARNING: 'myst' cross-reference target not found: 'features' [myst.xref_missing]
/Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/readme.md:14: WARNING: 'myst' cross-reference target not found: 'classification' [myst.xref_missing]
/Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/readme.md:15: WARNING: 'myst' cross-reference target not found: 'import' [myst.xref_missing]
/Users/tinevez/Development/MastodonWS/mastodon-documentation/docs/partC/deep_lineage/readme.md:16: WARNING: 'myst' cross-reference target not found: 'export' [myst.xref_missing]
generating indices... genindex done
writing additional pages... search done
copying images... [100%] docs/img/android-chrome-192x192.png
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 21 warnings.
```

**Comment by tinevez** [comment]
@stefanhahmann I can work on this, if you are ok?

**Comment by stefanhahmann** [comment]
> @stefanhahmann I can work on this, if you are ok?

Yes, sure. I would just like to know, what I did wrong to avoid the same mistake in the future.

**Comment by tinevez** [comment]
Actually I don't know. I think we need to add all the files to the `index.rst` TOC.

**Comment by stefanhahmann** [comment]
> Actually I don't know. I think we need to add all the files to the `index.rst` TOC.

Hm, maybe. I was trying to split contents to several pages, since before, it felt like a very long page, getting longer and longer and thus more difficult to consume for readers. But maybe, this is not supported by the readthedocs template that is used for this project?

**Comment by tinevez** [comment]
No it should be possible. At worst we can put links to the subpages in the main Deep-Lineage readme file.

**Comment by stefanhahmann** [comment]
> At worst we can put links to the subpages in the main Deep-Lineage readme file.

I had this thought as well, but this would allow navigation only in one direction. Let's see what it is possible..

**Pull request merged**
